### ISSUE TITLE
CLI leaks initial password into console

### ISSUE THREAD

**Issue by alexellis** [civo/cli-rubygem#17]
The CLI is currently leaking confidential data, i.e. the initial password.

This means it cannot be used in automation jobs or CI/CD.

Suggested fix:

- don't display this data
- add a specific flag to show it `--show-passwords`

![Screenshot 2019-07-10 at 19 54 54](https://user-images.githubusercontent.com/6358735/60996627-e2d59180-a34c-11e9-94b6-34251b76216e.png)

Example test job: https://travis-ci.org/alexellis/civo-prod-app/builds/556941496?utm_source=github_status&utm_medium=notification

**Comment by andyjeffries** [comment]
I'd actually prefer this to be a separate command and removed from the general show command:

```
$ civo instance password gitops-prod
YmnU8fQ0VZpIlrRS
```

**Comment by kaihoffman** [comment]
Will implement.

**Comment by andyjeffries** [comment]
Building off that simple command (and the public-ip one) - https://github.com/civo/cli/issues/18 - we should have a `-q` that just returns the field value, but by default it gives nice (colour coded) output.

**Comment by kaihoffman** [comment]
And just to confirm, remove `instance.initial_password` from `instance show` entirely?

**Comment by kaihoffman** [comment]
https://github.com/civo/cli/commit/982ba498e1d2c699839de2a04bd7684c933bb558 implements `password` and removes from `show`
