### ISSUE TITLE
kubernetes create error

### ISSUE THREAD

**Issue by scndel** [civo/cli-rubygem#46]
running `civo kubernetes create <name>`
with or without parameter triggers these errors :

**Ruby 2.6**

> /var/lib/gems/2.6.0/gems/flexirest-1.8.6/lib/flexirest/request.rb:595:in `handle_response': The POST to '/v2/kubernetes/clusters' returned a 403 status, which raised a Flexirest::HTTPForbiddenClientException with a body of: {"result":"forbidden","status":403,"reason":"Sorry, this feature is not enabled"}

**RUby 2.5**

> /var/lib/gems/2.5.0/gems/civo_cli-0.4.5/lib/kubernetes.rb:185:in `rescue in create': undefined method `reason' for #<String:0x00000000029b5940> (NoMethodError)

tried on _Ubuntu 16.04.6_ & _MacOS 10.14.6_
I regenerated my API key and updated it as current with CLI, it makes no difference.

**Comment by saiyam1814** [comment]
I just created the cluster using cli few minutes ago. Can you try creating any other civo resource?

**Comment by scndel** [comment]
Yes, I can create instance with CLI.
I think the answer is just *closed-access* like mentioned here : https://github.com/civo/cli#kubernetes-clusters
But before closing this issue, it would be nice to have a relevant response from API, independent from the Ruby version.

>

**Comment by andyjeffries** [comment]
Sorry, I don't know when this was fixed (apparently in June - so I don't know how you guys were still seeing it), but if I try to interact with k3s from the CLI using my personal account (which isn't Kube100 enabled) I get:

```
$ civo k3s ls
Sorry, this functionality is currently in closed beta and not available to the public yet
$ civo version
You are running the current v0.5.6 of Civo CLI
```

If you guys update your CLI to 0.5.6 do you still see the error/backtrace?
